spring:
  application:
    name: lemongrass
  config:
    import: optional:file:.env[.properties]
  
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 10s

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DATABASE:lemongrass}
    username: ${POSTGRESQL_USER:lemongrass}
    password: ${POSTGRESQL_PASS:12345678}
    hikari:
      poolName: Hikari
      auto-commit: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    generate-ddl: true
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    com.ttoannguyen.lemongrass: INFO

server:
  port: 8080

jwt:
  signer-key: ${JWT_SIGNER_KEY:SUc3vhm9LhF72WDw2z/IfSvCvjhYo8zJv1nfMNLGCDsKqA7wlJAPX5PyNZnpheAX}
  valid-duration: 3600
  refreshable-duration: 36000

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
