version: '3.9'
name: lemongrass
services:
  postgresql_lemongrass:
    container_name: postgresql_lemongrass
    image: postgres:16.2
    environment:
      - POSTGRES_USER=lemongrass
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=lemongrass
    ports:
      - "5432:5432"
    volumes:
      - lemongrass_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - lemongrass_network
volumes:
  lemongrass_data:
    name: lemongrass_data
    driver: local

networks:
  lemongrass_network:
    driver: bridge